data:
  img_size: 112
  batch_size: 2
  num_workers: 16
  volume_threshold: 10
  training_sets:
    - CTStroke_Tr
    - AMOS_Tr
    - CTOrgan_Tr
    - BRATS_Tr
    - AbdomenCT_Tr
    - ISLES_Tr
    - WORD_Tr
    - StanfordKnee_Tr
    - PancreasCt_Tr
    - MedSamDecathlon_Tr
    - Kits_Tr
    - SegThoracicOrgans_Tr
    - MultiModalWholeHeart_Tr
    - CovidCT_Tr
    - ONDRI_Tr
    - TotalSegmentator_Tr
    - LUNA_Tr
    - ProstateMRI_Tr
    - LiTS_Tr
    - MRIGlioblastoma_Tr
    - HealthyTotalBody_Tr
  validation_sets:
    - WORD_Val
    - AMOS_Val
    - ONDRI_Val