model:
  model_type: vit_l
  work_dir: ./work_dir
  task_name: debug
  lr: 8e-04
  weight_decay: 0.1
  lr_scheduler: multisteplr
  step_size: 
    - 120
    - 160
    - 190
  gamma: 0.1
  largest_first: true
  click_type: random
  multi_click: true
  bbox_first: false
  num_clicks: 11
  logging_batches_idx:
    - 1
    - 2
    - 3
    - 4
    - 5
  checkpoint: null